export const BUYING_GUIDES = {
  "telefon-alma-rehberi": {
    shortLabel: "Telefon",
    categorySlug: "telefon",
    eyebrow: "Satın alma rehberi",
    title: "Telefon alırken nelere dikkat etmelisin?",
    description: "İhtiyacına, bütçene ve kullanım alışkanlıklarına uygun telefonu seçmek için kısa ve net rehber.",
    search: "telefon",
    accent: "from-violet-950 via-bw-950 to-bw-900",
    glow: "bg-violet-500/30",
    steps: [
      ["Kullanımını belirle", "Sosyal medya, kamera, oyun, iş veya günlük kullanım: önceliğini netleştir. Böylece gereksiz özelliklere para vermezsin."],
      ["Ekran ve boyut", "Tek elle kullanım için kompakt modelleri; video, oyun ve üretkenlik için daha büyük, yüksek yenileme hızlı ekranları değerlendir."],
      ["Kamera ihtiyacı", "Sadece megapiksele bakma. Gece çekimi, sabitleme, portre ve video kalitesi için örnek çekimleri incele."],
      ["Pil ve şarj", "Gün boyu kullanım için pil kapasitesini, hızlı şarj desteğini ve kutudan adaptör çıkıp çıkmadığını kontrol et."],
      ["Depolama ve güncelleme", "Fotoğraf/video çekiyorsan en az 128 GB düşün. Yazılım güncelleme süresi uzun modeller daha uzun ömürlü olur."],
    ],
    checklist: ["IMEI ve cihaz kaydını doğrula", "Ekran, kasa ve kameraları test et", "Pil sağlığını ve şarj girişini kontrol et", "Kutu, fatura ve aksesuarları sor", "Takas değeri için net fotoğraflar hazırla"],
  },
  "bilgisayar-alma-rehberi": {
    shortLabel: "Bilgisayar",
    categorySlug: "bilgisayar",
    eyebrow: "Satın alma rehberi",
    title: "Bilgisayar alırken nelere dikkat etmelisin?",
    description: "İş, okul, tasarım, oyun ve günlük kullanım için doğru bilgisayarı seçmenin pratik yolu.",
    search: "bilgisayar",
    accent: "from-sky-950 via-bw-950 to-bw-900",
    glow: "bg-sky-500/30",
    steps: [
      ["Kullanım senaryonu seç", "Ofis ve okul için hafif bir dizüstü; oyun ve tasarım için güçlü ekran kartlı bir sistem; ev kullanımı için masaüstü daha uygun olabilir."],
      ["İşlemci ve bellek", "Günlük kullanımda güncel bir orta seviye işlemci ve 8–16 GB RAM yeterlidir. Çoklu görev, tasarım ve oyun için 16 GB ve üstünü hedefle."],
      ["Depolama", "SSD, açılış ve uygulama hızını doğrudan etkiler. 512 GB iyi bir başlangıç; büyük dosyalar için yükseltilebilirlik avantajdır."],
      ["Ekran ve taşınabilirlik", "Dışarıda çalışıyorsan parlaklık ve pil ömrüne; masa başında çalışıyorsan ekran boyutu, çözünürlük ve bağlantılara öncelik ver."],
      ["İkinci el kontrolü", "Batarya, klavye, menteşe, ekran pikseli, fan sesi ve portları tek tek dene. Mümkünse kısa bir performans testi yap."],
    ],
    checklist: ["Cihazın seri numarası ve faturasını kontrol et", "Ekranda ölü piksel veya ışık sızması var mı bak", "Klavye, touchpad, webcam ve tüm portları dene", "Batarya ve şarj adaptörünü test et", "RAM/SSD yükseltme imkânını sor"],
  },
  "tablet-alma-rehberi": {
    shortLabel: "Tablet",
    categorySlug: "tablet",
    eyebrow: "Satın alma rehberi",
    title: "Tablet alırken nelere dikkat etmelisin?",
    description: "Not alma, çizim, eğitim ve eğlence için doğru tableti seçmenin kısa rehberi.",
    search: "tablet",
    accent: "from-cyan-950 via-bw-950 to-bw-900",
    glow: "bg-cyan-500/30",
    steps: [
      ["Ekranı amacına göre seç", "Not almak ve film izlemek için ekran boyutu ile çözünürlük önemlidir."],
      ["Kalem ve klavye desteğine bak", "Çizim veya ders notları için uyumlu kalem desteğini mutlaka kontrol et."],
      ["Depolama ihtiyacını hesapla", "Uygulama, oyun ve çevrim dışı içerikler için yeterli depolama seç."],
      ["İkinci elde test et", "Ekran dokunmatiğini, şarj girişini, kamerayı ve varsa kalemi dene."],
    ],
    checklist: ["Dokunmatik ekranın tamamını dene", "Kalem ve klavye uyumluluğunu sor", "Pil sağlığını kontrol et", "Şarj adaptörünü test et"],
  },
  "kulaklik-alma-rehberi": {
    shortLabel: "Kulaklık",
    categorySlug: "kulaklik",
    eyebrow: "Satın alma rehberi",
    title: "Kulaklık alırken nelere dikkat etmelisin?",
    description: "Müzik, toplantı ve oyun için sana uygun kulaklığı seç.",
    search: "kulaklık",
    accent: "from-fuchsia-950 via-bw-950 to-bw-900",
    glow: "bg-fuchsia-500/30",
    steps: [
      ["Kullanım biçimini belirle", "Günlük kullanımda konfor; oyun ve toplantıda mikrofon kalitesi öne çıkar."],
      ["Bağlantıyı seç", "Telefonunla uyumlu Bluetooth sürümüne ve çoklu cihaz desteğine bak."],
      ["Ses ve gecikmeyi dene", "Mümkünse sesi, mikrofonu ve gecikmeyi yerinde test et."],
    ],
    checklist: ["Sağ ve sol ses seviyesini dene", "Mikrofonu test et", "Şarj kutusunu kontrol et", "Pedlerde aşınma var mı bak"],
  },
  "kilif-alma-rehberi": {
    shortLabel: "Kılıf",
    categorySlug: "kilif-koruma",
    eyebrow: "Satın alma rehberi",
    title: "Kılıf ve ekran koruyucu seçme rehberi",
    description: "Cihazını korurken kullanım rahatlığını kaybetme.",
    search: "kılıf",
    accent: "from-slate-950 via-bw-950 to-bw-900",
    glow: "bg-slate-400/25",
    steps: [
      ["Model uyumunu doğrula", "Kamera ve tuş kesiklerinin cihazınla birebir uyumlu olduğundan emin ol."],
      ["Koruma seviyesini seç", "Darbe emici kenarlar ve yükseltilmiş kamera çerçevesi korumayı artırır."],
      ["Malzemeyi değerlendir", "Silikon, sert plastik veya deri seçeneklerini tutuş ve kullanımına göre karşılaştır."],
    ],
    checklist: ["Telefon modelini doğrula", "Kamera korumasına bak", "Kablosuz şarj uyumluluğunu sor", "Ekran koruyucuyla birlikte kontrol et"],
  },
  "sarj-alma-rehberi": {
    shortLabel: "Şarj",
    categorySlug: "sarj-kablo",
    eyebrow: "Satın alma rehberi",
    title: "Şarj ve kablo alırken nelere dikkat etmelisin?",
    description: "Cihazına güvenli ve uygun şarj aksesuarını seç.",
    search: "şarj",
    accent: "from-amber-950 via-bw-950 to-bw-900",
    glow: "bg-amber-500/30",
    steps: [
      ["Güç ihtiyacını öğren", "Telefon, tablet veya bilgisayarının desteklediği watt değerini kontrol et."],
      ["Kablo standardını kontrol et", "USB-C, Lightning ve veri aktarım ihtiyaçlarına uygun kabloyu seç."],
      ["Güvenliği öne al", "Aşırı ısınma ve kısa devre koruması olan güvenilir ürünleri tercih et."],
    ],
    checklist: ["Watt değerini eşleştir", "Kablo ucunu doğrula", "Adaptör ve kabloyu beraber dene", "Kırık veya ısınma belirtisi var mı bak"],
  },
  "aksesuar-alma-rehberi": {
    shortLabel: "Aksesuar",
    categorySlug: "aksesuar",
    eyebrow: "Satın alma rehberi",
    title: "Aksesuar seçme rehberi",
    description: "Günlük kullanımını kolaylaştıracak doğru teknoloji aksesuarını bul.",
    search: "aksesuar",
    accent: "from-emerald-950 via-bw-950 to-bw-900",
    glow: "bg-emerald-500/30",
    steps: [
      ["İhtiyacını belirle", "Stand, tutucu ve adaptör gibi ürünleri kullanım senaryona göre seç."],
      ["Uyumluluğu kontrol et", "Cihazının ölçüleri, bağlantısı ve taşıma kapasitesiyle eşleştiğinden emin ol."],
      ["Kaliteyi incele", "Malzeme, bağlantı noktaları ve hareketli parçaları kontrol et."],
    ],
    checklist: ["Cihaz ölçüsünü doğrula", "Bağlantı tipini kontrol et", "Malzemeyi incele", "Eksik parça var mı bak"],
  },
  "akilli-saat-alma-rehberi": {
    shortLabel: "Akıllı saat",
    categorySlug: "akilli-saat",
    eyebrow: "Satın alma rehberi",
    title: "Akıllı saat alırken nelere dikkat etmelisin?",
    description: "Sağlık takibi, spor ve bildirimler için doğru akıllı saati seç.",
    search: "akıllı saat",
    accent: "from-rose-950 via-bw-950 to-bw-900",
    glow: "bg-rose-500/30",
    steps: [
      ["Telefon uyumluluğunu doğrula", "Saatin iOS veya Android cihazınla tam uyumunu kontrol et."],
      ["Pil ve kullanım süresine bak", "Günlük şarj alışkanlığına uygun pil ömrünü seç."],
      ["Sensörleri değerlendir", "Spor, uyku ve sağlık takibi için ihtiyacın olan sensörleri karşılaştır."],
    ],
    checklist: ["Telefon uyumluluğunu sor", "Ekran ve dokunmatiği dene", "Şarj kablosunu kontrol et", "Kordon ve kasa aşınmasını incele"],
  },
  "oyun-alma-rehberi": {
    shortLabel: "Oyun",
    categorySlug: "oyun-konsol",
    eyebrow: "Satın alma rehberi",
    title: "Oyun ekipmanı alırken nelere dikkat etmelisin?",
    description: "Konsol ve oyuncu ekipmanını doğru seçmek için kısa rehber.",
    search: "oyun",
    accent: "from-blue-950 via-bw-950 to-bw-900",
    glow: "bg-blue-500/30",
    steps: [
      ["Platformunu belirle", "Konsol, PC veya mobil oyunculuğa göre uyumlu ekipman seç."],
      ["Bağlantı ve gecikmeyi kontrol et", "Kablosuz cihazlarda gecikme ve bağlantı kararlılığına bak."],
      ["İkinci elde tüm tuşları dene", "Kol, joystick ve konsolda her tuş ile bağlantı noktasını test et."],
    ],
    checklist: ["Tüm tuşları dene", "Kablo ve adaptörü kontrol et", "Bağlantı testini yap", "Hesap kilidi olmadığından emin ol"],
  },
};

export const BUYING_GUIDE_LIST = Object.entries(BUYING_GUIDES).map(([slug, guide]) => ({ slug, ...guide }));

export const CATEGORY_GUIDE_SLUGS = {
  telefon: "telefon-alma-rehberi",
  bilgisayar: "bilgisayar-alma-rehberi",
  tablet: "tablet-alma-rehberi",
  kulaklik: "kulaklik-alma-rehberi",
  "kilif-koruma": "kilif-alma-rehberi",
  "sarj-kablo": "sarj-alma-rehberi",
  aksesuar: "aksesuar-alma-rehberi",
  "akilli-saat": "akilli-saat-alma-rehberi",
  "oyun-konsol": "oyun-alma-rehberi",
};

export function getGuideCategorySlug(guideSlug) {
  return BUYING_GUIDES[guideSlug]?.categorySlug || null;
}
